In [5]:
!conda list

# packages in environment at C:\Users\jaehee\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39haa95532_0  
alabaster                 0.7.12             pyhd3eb1b0_0  
anaconda                  2022.10                  py39_0  
anaconda-client           1.11.0           py39haa95532_0  
anaconda-navigator        2.3.1            py39haa95532_0  
anaconda-project          0.11.1           py39haa95532_0  
anyio                     3.5.0            py39haa95532_0  
appdirs                   1.4.4              pyhd3eb1b0_0  
argon2-cffi               21.3.0             pyhd3eb1b0_0  
argon2-cffi-bindings      21.2.0           py39h2bbff1b_0  
arrow                     1.2.2              pyhd3eb1b0_0  
astroid                   2.11.7           py39haa95532_0  
astropy                   5.1              py39h080aedc_0  
atomicwrites              1.4.0                      py_0  
attrs                     21.4.0   

In [ ]:
list는 섞여서 자료를 가질 수 있다.
numpy array는 동일한 자료

In [6]:
import numpy as np

In [10]:
# 1D array(1차원 배열) 
# ndarray class로부터 객체를 생성한다.
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
type(ar)

numpy.ndarray

In [12]:
ar.shape  # 객체가 갖는 속성을 보여줌 : .shape

(10,)

In [14]:
# 모든 요소가 같은 자료형이어야 하고, 접근의 개수에 제한없이 삽입
ar2 = np.array([0.1, 12, 50 ,2, 3.14])
ar2

array([ 0.1 , 12.  , 50.  ,  2.  ,  3.14])

In [15]:
ar.dtype

dtype('int32')

In [16]:
ar2.dtype

dtype('float64')

In [17]:
x = np.array([1,2,3,4], dtype = 'f')
x.dtype

dtype('float32')

In [18]:
x[0]+x[1]

3.0

In [19]:
x = np.array([1,2,3], dtype = 'U')
x.dtype

dtype('<U1')

In [24]:
x[1]+x[2]

'23'

In [26]:
# inf : 무한대 nan : 정의할 수 업는 숫자
np.array([0,1,-1,0])/ np.array([1,0,0,0])

C:\Users\jaehee\AppData\Local\Temp\ipykernel_10964\567499939.py:2: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0,1,-1,0])/ np.array([1,0,0,0])
C:\Users\jaehee\AppData\Local\Temp\ipykernel_10964\567499939.py:2: RuntimeWarning: invalid value encountered in true_divide
  np.array([0,1,-1,0])/ np.array([1,0,0,0])


array([  0.,  inf, -inf,  nan])

In [33]:
# 백터와 연산
data = [0,1,2,3,4,5,6,7,8,9]
answer = [2*d for d in data]
print(answer)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [35]:
x = np.array(data)
x* 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
list_samp = [_ for _ in range(3)]
print(list_samp * 5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [37]:
a = np.array([1,2,3])
b = np.array([10,20,30])
2 * a+b

array([12, 24, 36])

In [38]:
a == 2

array([False,  True, False])

In [39]:
b > 10

array([False,  True,  True])

In [40]:
(a == 2) & (b > 10) # and와 비슷함 &

array([False,  True, False])

In [41]:
# 2차원 배열 만들기 shape: (2,3) 앞에가 세로 뒤에가 가로
c = np.array([[0,1,2],
              [3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [42]:
c.shape

(2, 3)

In [43]:
# 행의 갯수 세로
len(c)

2

In [44]:
# 열의 갯수 가로
len(c[0])

3

In [46]:
y = np.array([[10,20,30,40],
             [50,60,70,80]])
y

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [47]:
# 3차원 배열 (깊이, 행, 열)(높, 가, 세)
d = np.array([[[1,2,3,4],
               [5,6,7,8],
               [9,10,11,12]],
              [[11,12,13,14],
               [15,16,17,18],
               [19,20,21,22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [48]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [49]:
d.shape

(2, 3, 4)

In [50]:
# 배열의 차원과 크기 알아내기
a = np.array([1,2,3])

print(a.ndim)   # ndim 차원을 알 수 있다
print(a.shape)

1
(3,)


In [51]:
a = np.array([0,1,2,3,4])
a[2]

2

In [52]:
a[-1]

4

In [71]:
a = [[1,2,3,4],[5,6,7,8]]

In [83]:
a[0][0:3]

[1, 2, 3]

In [61]:
a = np.array([[0,1,2],
              [3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [62]:
a[0,0]

0

In [68]:
a[1,2]

5

In [70]:
a[-2,-2]

1

In [91]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [92]:
a[0, :]

array([0, 1, 2, 3])

In [93]:
a[:, 1]

array([1, 5])

In [94]:
a[1, 1:]

array([5, 6, 7])

In [95]:
a[:2, :2]

array([[0, 1],
       [4, 5]])

In [96]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [127]:
m[1,2],m[2,4],m[1, 1:3],m[1:, 2],m[:2, 3:]

(7,
 14,
 array([6, 7]),
 array([ 7, 12]),
 array([[3, 4],
        [8, 9]]))

In [128]:
# 배열 생성
c = np.zeros((5,2), dtype = 'i')

In [129]:
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [131]:
d = np.zeros(5,dtype='U4')

In [132]:
d

array(['', '', '', '', ''], dtype='<U4')

In [133]:
d[0] = "abc"
d[1] = "abcd"
d[2] = "ABCDE"
d

array(['abc', 'abcd', 'ABCD', '', ''], dtype='<U4')

In [134]:
e = np.ones((2,3,4),dtype="i8")

In [135]:
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [136]:
f = np.ones_like(b, dtype="f")

In [137]:
f

array([1., 1., 1.], dtype=float32)

In [139]:
g = np.empty((4,3))

In [140]:
g

array([[8.61202913e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.23358265e-038],
       [4.19949997e+175, 4.08763581e-033, 6.12265291e+169],
       [1.93217555e+184, 3.92978878e-061, 1.86957139e-051]])

In [141]:
# arange명령 : numpy버전의 range 명령이다.
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
np.arange(3,21,2) # 시작, 끝(포함x), 상승 값

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [143]:
# linspace 명령 : 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할
ex = np.linspace(0,100,5)   # 5 = 구간이요

In [144]:
ex

array([  0.,  25.,  50.,  75., 100.])

In [145]:
ex2 = np.logspace(0, 100, 5)

In [146]:
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [147]:
# 전치 연산 : 2차 배열의 전치 연산은 행과 열을 바꾸는 작업

A = np.array([[1,2,3],[4,5,6]])

In [148]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [149]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [150]:
# 배열의 크기 변형 : reshape 1차원 행렬을 2차원 행렬로 변경개능
a= np.arange(12)

In [151]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [152]:
b = a.reshape(3,4)

In [153]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
a.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
a.reshape(2,2,-1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [156]:
a.reshape(2,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [158]:
# 다차원 배열을 1차원으로 만들기 위헤서 flatten, ravel메서드 사용

a.reshape(2,2,-1).flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [159]:
x = np.arange(5)

In [161]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
# 배열 연결 : 행의 수나 같은두개 이상의 배열을 연결하여 더 큰 배열을 만들 때 쓰는 명령

hstack : 행의 수가 같은 두 개 이상의 배열을 옆으로 연결하여 열의 수가 더 많은 배열을 만든다
vstack : 수직
dstack : 제일 안쪽 차원?
stack :
r__ 
c__
tile
hstack

In [186]:
d1 = np.ones((4,5))
d2 = np.zeros((4, 5))
d3 = np.arange(20).reshape(4,5)

In [187]:
d1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [183]:
d2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [184]:
d3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [188]:
np.stack([d1,d2,d3], axis = 1)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  1.,  2.,  3.,  4.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 5.,  6.,  7.,  8.,  9.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [10., 11., 12., 13., 14.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [15., 16., 17., 18., 19.]]])

In [192]:
np.stack([d1,d2,d3], axis = 2)

array([[[ 1.,  0.,  0.],
        [ 1.,  0.,  1.],
        [ 1.,  0.,  2.],
        [ 1.,  0.,  3.],
        [ 1.,  0.,  4.]],

       [[ 1.,  0.,  5.],
        [ 1.,  0.,  6.],
        [ 1.,  0.,  7.],
        [ 1.,  0.,  8.],
        [ 1.,  0.,  9.]],

       [[ 1.,  0., 10.],
        [ 1.,  0., 11.],
        [ 1.,  0., 12.],
        [ 1.,  0., 13.],
        [ 1.,  0., 14.]],

       [[ 1.,  0., 15.],
        [ 1.,  0., 16.],
        [ 1.,  0., 17.],
        [ 1.,  0., 18.],
        [ 1.,  0., 19.]]])

In [193]:
np.stack([d1,d2,d3], axis = 0)

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19.]]])

In [189]:
np.stack([d1,d2,d3], axis = 1).shape

(4, 3, 5)

In [163]:
# vstack
b1 = np.ones((2,3)) 

In [164]:
b1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [165]:
b2 = np.ones((3,3))

In [168]:
b2

array([[1., 1., 1.],
       [1., 1., 1.]])

In [169]:
np.vstack([b1,b2])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [170]:
# dstack : 깊이 방향으로 배열을 합친다.

c1 = np.ones((3,4))

In [171]:
c1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [172]:
c2 = np.zeros((3,4))

In [173]:
c2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [177]:
np.dstack([c1, c2])

array([[[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]],

       [[1., 0.],
        [1., 0.],
        [1., 0.],
        [1., 0.]]])

In [ ]:
# stack 명령은 dstack 기능을 확장한 것으로 dstack 처럼 마지막 차원으로


In [194]:
# r__ 메서드 hstack 명령과 비슷하게 배열을 좌우로 연결.

np.r_[np.array([1,2,3]), np.array([4,5,6])]

array([1, 2, 3, 4, 5, 6])

In [196]:
# c_ 메서드는 배열의 차원을 증가시킨 후 좌우로 연결합니다

np.c_([np.array([1,2,3]), np.array([4,5,6])

SyntaxError: unexpected EOF while parsing (4256299995.py, line 3)

In [ ]:
# tile 명령은 동일한 배열을 반복하여 연결

np.arange(6).reshp

In [212]:
a = np.zeros((3,3))
b = np.ones((3,2))
c = np.arange(10, 151, 10)
c = c.reshape(3,5)
d = np.hstack((a, b))
e = np.vstack((d, c))
f = np.tile(e, (2,1))

In [213]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [214]:
b

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [215]:
c

array([[ 10,  20,  30,  40,  50],
       [ 60,  70,  80,  90, 100],
       [110, 120, 130, 140, 150]])

In [216]:
d

array([[0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.],
       [0., 0., 0., 1., 1.]])

In [217]:
e

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [218]:
f

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [231]:
z = np.zeros([3,3])
o = np.ones([3,2])
n= np.reshape(np.arange(10,160,10),(3,-1))
res = np.tile(np.vstack([np.hstack(

In [ ]:
# 백터화 연산

In [219]:
x = np.arange(1, 10001)
y = np.arange(10001, 20001)

In [220]:
%%time
z = np.zeros_like(x)
for i in range(10000):
    z[i] = x[i]+y[i]

Wall time: 8.98 ms


In [221]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
c = np.array([1,2,3,4])

In [224]:
np.all (a == b)

False

In [225]:
np.all (a == c)

True

In [ ]:
# 스칼라와 벡터/행렬의 곱셈

In [226]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [227]:
100*x

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [228]:
x = np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [229]:
100*x

array([[   0,  100,  200,  300],
       [ 400,  500,  600,  700],
       [ 800,  900, 1000, 1100]])

In [ ]:
# 브로드캐스팅 :  산술 연산을 할려면 shape 가 같아야됨

In [ ]:
모양이 다른 배열 간의 연산이 가능하도록 배열의 크기를 변환시켜주는 브로드캐스팅을 지원

In [230]:
a = np.array([1.0,2.0,3.0])
b = 2.0
a * b

array([2., 4., 6.])

In [ ]:
확장이 가능한 경우 : 배열의 shape을 우측 정렬하고, 각 차원별로 숫자를 비교

In [ ]:
차원 축소 연산 : 최대/최소 : min, argmin,
 통계 : sum, mean
불 : 

In [ ]:
sum() : 해당 배열의 합산 결과를 반환 2차원 이상일 때에는 axis 키워드 인수 사용가능

In [233]:
x = np.arange(12).reshape(3,-1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [235]:
x = np.arange(20).reshape(2,5,-1)
x

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [237]:
x.min()

0

In [239]:
np.min(x)

0

In [241]:
x.min(axis=0)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [251]:
# 차원 축소 연산= argmin()
x = np.arange(20).reshape(2,5,-1)

# x.ardmin(axis=0)

In [252]:
x.argmax()

19

In [253]:
np.argmax(x)

19

In [254]:
x.argmax(axis=0)

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]], dtype=int64)

In [255]:
np.argmax(x,axis =1)

array([[4, 4],
       [4, 4]], dtype=int64)

In [256]:
x.argmax(axis=2)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int64)

In [1]:
import numpy as np
import random


In [ ]:
# 차원 축소 연산
- mean() :평균
- median() : 중앙값
- np.any() : 요소가 단 하나라도 T이면 T, 모두 F일 때는 F를 반환
- np.all() : 모든 요소가 T이면 T, 하나라도 F이면 F를 반환


In [261]:
a =np.zeros((100,100), dtype=np.int64)
a

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [262]:
np.any(a != 0)

False

In [263]:
np.all(a == a)

True

In [281]:
practice = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2],
                    [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
                    [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
                    [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
                    [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])


In [283]:
practice.max(),practice.sum(axis=0),practice.max(axis=0),practice.mean(axis=1),practice.min(axis=1)



(9.0,
 array([20.1, 27. , 23.6, 26. , 28.2, 26.5]),
 array([8.2, 8.8, 8. , 9. , 7.7, 8.9]),
 array([5.33333333, 5.11666667, 5.71666667, 4.11666667, 4.95      ]),
 array([1.1, 2.7, 0.7, 0.2, 2.7]))

In [284]:
# 정렬  자체변화(in-place)메서드이므로 주의 필요
# 정렬하는 것이 아니라 순서만 알고 싶다면 argsort명령을 사용
a = np.array([42,38,12,25])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [285]:
a[j]

array([12, 25, 38, 42])

In [286]:
np.sort(a)

array([12, 25, 38, 42])

In [287]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [288]:
print(a[[0,1,2],[0,1,0]])

[1 4 5]


In [289]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [293]:
print(a[:, [0,1,0]])

[[1 2 1]
 [3 4 3]
 [5 6 5]]


In [301]:
scores = np.array([[1, 2, 3, 4],
                   [46, 99, 100, 71],
                   [81, 59, 90, 100]])
row = np.argsort(scores[1, :])

In [302]:
row

array([0, 3, 1, 2], dtype=int64)

In [303]:
scores[:, row]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [304]:
# 표본 평균 : np.mean(x)
# 분산 : np.var(x) ddof=1
# 표준 편차 : np.std(x)
# 중앙값 : np.median(x)
# 사분위수 : 1사분위수는 25% 백분위수와 같다. 2사 분위수는 중앙값 3사분위수는 75%
# 난수 발생과 카운팅 
# 시드 설정하기 
np.random.seed(0)

In [305]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [306]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [307]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [308]:
np.random.seed(0)

In [309]:
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [310]:
np.random.rand(10)

array([0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152,
       0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606])

In [311]:
np.random.rand(10)

array([0.0871293 , 0.0202184 , 0.83261985, 0.77815675, 0.87001215,
       0.97861834, 0.79915856, 0.46147936, 0.78052918, 0.11827443])

In [312]:
# 데이터의 순서 바꾸기 
x = np.arange(10) 
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [313]:
np.random.shuffle(x)   #임의로 순서를 바꿔줌
x

array([3, 6, 4, 5, 2, 9, 7, 8, 1, 0])

In [314]:
np.random.shuffle(x)
x

array([5, 7, 6, 1, 9, 3, 0, 2, 8, 4])

In [315]:
# 데이터 샘플링 : choice 함수를 사용 
# a: 배열이면 원래의 데이터 size: 정수 replace:불리언 p

np.random.choice(5, 5, replace=False) # shuffle 명령과 같다

array([3, 2, 1, 4, 0])

In [316]:
np.random.choice(5, 3, replace=False)

array([3, 0, 2])

In [317]:
np.random.choice(5,10)

array([0, 1, 1, 1, 1, 3, 3, 2, 3, 0])

In [318]:
np.random.choice(5, 10, p =[0.1, 0, 0.3, 0.6, 0])

array([2, 2, 3, 3, 3, 2, 2, 2, 3, 2])

In [319]:
# 난수 생성 
# rand  : 
# randn : 기댓값(mean)이 0이고 표준편차가 1인 표준 정규 분포를 따르는 난수를 생성
# randint : (low, high=None, size=None) 만약 high를 입력하지 않으면 0과 low사이의 숫자를, 
# high를 입력하면 low와 high 사이의 숫자를 출력
np.random.rand(10)

array([0.46631077, 0.24442559, 0.15896958, 0.11037514, 0.65632959,
       0.13818295, 0.19658236, 0.36872517, 0.82099323, 0.09710128])

In [320]:
np.random.rand(3,5)

array([[0.83794491, 0.09609841, 0.97645947, 0.4686512 , 0.97676109],
       [0.60484552, 0.73926358, 0.03918779, 0.28280696, 0.12019656],
       [0.2961402 , 0.11872772, 0.31798318, 0.41426299, 0.0641475 ]])

In [321]:
np.random.randn(10)

array([ 0.61980106,  1.79116846,  0.17100044, -1.72567135,  0.16065854,
       -0.85898532, -0.20642094,  0.48842647, -0.83833097,  0.38116374])

In [322]:
np.random.randn(3, 5)

array([[-0.99090328,  1.01788005,  0.3415874 , -1.25088622,  0.92525075],
       [-0.90478616,  1.84369153,  1.52550724, -1.44553558,  0.37716061],
       [-0.07055723,  0.60415971,  0.472149  ,  0.81991729,  0.90751962]])

In [324]:
np.random.randint(10, size=10)

array([8, 0, 8, 5, 9, 0, 9, 6, 5, 3])

In [336]:
np.random.seed(0)
k = [np.random.randint(0, 2) for _ in range(100) ]
np.mean(k)

0.56

In [337]:
np.random.seed(0)
res = np.random.randint(0, 2, 100)
res.sum() / len(res)

0.56

In [338]:
np.random.seed(0)
a= np.random.randint(2, size=100)
np.mean(a)

0.56

In [339]:
# 정수 데이터 카운팅 : unique명령, bincount명령으로 데이터 값을 분석할 수 있다.
# unique()함수는 데이터에서 중복된 값을 제거하고 중복되지 않는 값의 리스트를 출력
np.bincount([1,1,2,2,2,3], minlength=6)

array([0, 2, 3, 1, 0, 0], dtype=int64)