In [1]:
# numpy 복습

In [2]:
import numpy as np

In [3]:
# 1차원 배열
ar = np.array([_ for _ in range(10)])
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
ar.shape

(10,)

In [5]:
type(ar)

numpy.ndarray

In [6]:
ar2 = np.array([0.1, 5, 4, 12, 0.5])
ar2

array([ 0.1,  5. ,  4. , 12. ,  0.5])

In [7]:
# 자료형을 명시적으로 작성하려면 키워드 인자 dtype을 사용
ar2.dtype

dtype('float64')

In [8]:
ar.dtype

dtype('int32')

In [9]:
x = np.array([1,2,3], dtype = 'f')
x.dtype

dtype('float32')

In [10]:
x[0] + x[1]

3.0

In [11]:
x = np.array([1,2,3], dtype = 'U')
x.dtype

dtype('<U1')

In [12]:
x[0] + x[2]

'13'

In [13]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\jaehee\AppData\Local\Temp\ipykernel_10364\2068585620.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\jaehee\AppData\Local\Temp\ipykernel_10364\2068585620.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [14]:
np.log(0)

C:\Users\jaehee\AppData\Local\Temp\ipykernel_10364\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [15]:
data = [0,1,2,3,4,5,6,7,8,9]
answer = [2*i for i in data]
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [16]:
x = np.array(data)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
x * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
list_samp = [_ for _ in range(3)]
print(list_samp*5)

[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]


In [19]:
a = np.array([1,2,3])
b = np.array([10,20,30])

2 * a+b

array([12, 24, 36])

In [20]:
a == 2

array([False,  True, False])

In [21]:
b > 10

array([False,  True,  True])

In [22]:
(a == 2) & (b>10)   # and와 같고 가로 쳐줘야된다.

array([False,  True, False])

In [23]:
# 2차열 배열
c = np.array([[0,1,2],[3,4,5]])
c

array([[0, 1, 2],
       [3, 4, 5]])

In [24]:
len(c)

2

In [25]:
len(c[0])

3

In [26]:
c.shape

(2, 3)

In [27]:
q = np.array([[10,20,30,40],
              [50,60,70,80]])

In [28]:
q

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [29]:
np.array([[_ for _ in range(10,50,10)],
          [i for i in range(50,90,10)]])

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [30]:
# 3차열 배열
d = np.array([[[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]],
             [[11,12,13,14],
              [15,16,17,18],
              [19,20,21,22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [31]:
len(d), len(d[0]), len(d[0][0])

(2, 3, 4)

In [32]:
d.shape

(2, 3, 4)

In [33]:
a = np.array([1,2,3])
print(a.ndim)  # 차원을 알려준다.
print(a.shape)

1
(3,)


In [34]:
a = np.array([0,1,2,3,4])

a[2]

2

In [35]:
a[-1]

4

In [36]:
#배열의 인덱싱
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [37]:
a[0,0]

0

In [38]:
a[0,2]

2

In [39]:
a[1,1]

4

In [40]:
a = np.array([[0,1,2,3],[4,5,6,7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [41]:
a[0, :]

array([0, 1, 2, 3])

In [42]:
a[:, 1]

array([1, 5])

In [43]:
a[1, 1:]

array([5, 6, 7])

In [44]:
a[:, :2]

array([[0, 1],
       [4, 5]])

In [45]:
m = np.array([[0,1,2,3,4],
              [5,6,7,8,9],
              [10,11,12,13,14]])
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
m[1,2]

7

In [47]:
m[2,4]

14

In [48]:
m[1,1:3]

array([6, 7])

In [49]:
m[1:, 2]

array([ 7, 12])

In [50]:
m[:2,3:]

array([[3, 4],
       [8, 9]])

In [51]:
a = np.zeros(5)   # 배열 생성 : zeros,ones,empty,arange, linspace,logspace
a

array([0., 0., 0., 0., 0.])

In [52]:
c = np.zeros((5,2), dtype = 'i')
c

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [53]:
d = np.zeros(5, dtype = 'U4')
d

array(['', '', '', '', ''], dtype='<U4')

In [54]:
d[0] = 'abc'
d[1] = 'abcd'
d[2] = 'abcde'

In [55]:
d

array(['abc', 'abcd', 'abcd', '', ''], dtype='<U4')

In [56]:
e = np.ones((2,3,4), dtype = 'i8')
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int64)

In [57]:
f = np.ones_like(b, dtype='f')
f

array([1., 1., 1.], dtype=float32)

In [58]:
g = np.empty((4,3))

In [59]:
d

array(['abc', 'abcd', 'abcd', '', ''], dtype='<U4')

In [60]:
g

array([[7.26292561e-312, 3.16202013e-322, 0.00000000e+000],
       [0.00000000e+000, 1.08221785e-312, 3.93514273e-062],
       [1.04000526e-042, 8.84881082e+165, 5.69632620e-038],
       [6.89493147e-042, 6.59220556e-066, 7.34872386e-043]])

In [61]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
np.arange(3,21,2)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19])

In [63]:
ex = np.linspace(0,100,5)
ex

array([  0.,  25.,  50.,  75., 100.])

In [64]:
ex2 = np.logspace(0,100,5)
ex2

array([1.e+000, 1.e+025, 1.e+050, 1.e+075, 1.e+100])

In [65]:
# 전치 연산 : T
A = np.array([[1,2,3],[4,5,6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [66]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [67]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [68]:
b = a.reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [70]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [71]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [72]:
x.reshape(1,5)

array([[0, 1, 2, 3, 4]])

In [73]:
x.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [74]:
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [75]:
hstack
vstack
dstack
stack
r_
c_
tile
hstack

NameError: name 'hstack' is not defined

In [ ]:
# hstack
a1 = np.ones((2,3))
a1

In [ ]:
a2 = np.zeros((2,3))
a2

In [ ]:
np.hstack([a1,a2])

In [ ]:
# vstack
b1 = np.ones((2,3))
b1

In [ ]:
b2 = np.zeros((3,3))
b2

In [ ]:
np.vstack([b1,b2])

In [ ]:
# dstack
c1 = np.ones((3,4))
c1

In [ ]:
c2 = np.zeros((3,4))
c2

In [ ]:
np.dstack([c1,c2])

In [ ]:
c = np.stack([c1,c2])
c

In [ ]:
c.shape

In [ ]:
c = np.stack([c1,c2], axis =1)
c

In [ ]:
c.shape

In [ ]:
np.r_[np.array([1,2,3]), np.array([4,5,6])]

In [ ]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

In [ ]:
a = np.array([[0,1,2],[3,4,5]])
np.tile(a,2)

In [ ]:
np.tile(a,(3,2))

In [ ]:
a = np.zeros((3,3))
b = np.ones((3,2))
c = np.hstack((a,b))
d = np.arange(10,151,10)
d = d.reshape(3,5)
e = np.vstack([c,d])
f = np.tile(e,(2,1))
f

In [ ]:
#차원 축소 연산
최대/최소 : min, max, argmin, argmax
통계 : sum, mean, median, std, var
불리언 : all, any

In [ ]:
x = np.array([1,2,3,4])
x

In [ ]:
np.sum(x)

In [ ]:
x.sum()

In [ ]:
x = np.arange(12).reshape(3,-1)
x

In [ ]:
x.sum(axis=0)

In [ ]:
x.sum(axis=1)

In [ ]:
x = np.arange(20).reshape(2,5,-1)
x

In [ ]:
x.min(axis=0)

In [ ]:
np.min(x, axis=1)

In [ ]:
p = np.array([[1.1, 7.1, 8.0, 2.1, 6.5, 7.2], 
 [2.7, 5.2, 3.3, 9.0, 7.7, 2.8],
 [0.7, 8.8, 4.2, 8.9, 4.3, 7.4],
 [8.2, 1.1, 5.4, 2.9, 6.9, 0.2],
 [7.4, 4.8, 2.7, 3.1, 2.8, 8.9]])
p

In [ ]:
p.max()

In [ ]:
p.sum(axis=0)

In [ ]:
p.max(axis=0)

In [ ]:
p.mean(axis=1)

In [ ]:
p.min(axis=1)

In [ ]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
a

In [ ]:
np.sort(a)

In [ ]:
np.sort(a, axis=0)

In [ ]:
a = np.array([[4,3,5,7],
              [1,12,11,9],
              [2,15,1,14]])
a

In [ ]:
a.sort(axis=1)

In [ ]:
a

In [ ]:
a = np.array([42,38,12,25])
j = np.argsort(a)
j

In [ ]:
a[j]

In [ ]:
np.sort(a)

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
a

In [ ]:
print(a[[0,1,2],[0,1,0]])

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
a

In [ ]:
print(a[:, [0,1,0]])

In [ ]:
scores = np.array([[1,2,3,4],
              [46,99,100,71],
              [81,59,90,100]])
scores

In [ ]:
row = np.argsort(scores[1,:])
row

In [ ]:
print(scores[:,row])

In [ ]:
평균 : np.mean(x)
분산 : np.var(x)
표준편차 : np.std(x)


In [ ]:
np.random.seed(0)

In [ ]:
coin = np.random.randint(0, 2, 100)
coin.sum()/len(coin)

In [ ]:
np.random.seed(0)
k = [np.random.randint(0, 2) for _ in range(100) ]
np.mean(k)

In [ ]:
np.random.seed(0)
a= np.random.randint(2, size=100)
np.mean(a)

In [ ]:
np.random.seed(0)
a = np.random.randint(1,7,100)
a.sum()/len(a)

In [ ]:
# 연습문제
np.random.seed(0)
k = [np.random.randint(1, 7) for _ in range(100)]
np.mean(k)

In [ ]:
a = np.array([[1,2,3],
              [4,5,6]])
b = np.array([[7,8,9],
              [10,11,12]])
a + b

In [ ]:
(np.array([[1,2,3],[4,5,6]])) + (np.array([[7,8,9],[10,11,12]]))

In [ ]:
a = np.arange(1,10)
a * 3

In [ ]:
x = np.zeros(10)
x[4] = 1
x

In [ ]:
x = np.arange(50)
x[::-1]

In [ ]:
np.zeros((3,3,3), dtype = 'U10')

In [ ]:
#np.full() 하나의 특정 값으로 배열의 값을 채우고 싶을 때 씀
# shape - 채울 값 / dtype

In [ ]:
a = np.full((3,3,3),"playdata",dtype = 'U8')
a

In [ ]:
a = np.arange(2,41,2)
a.reshape(2,2,5)

In [ ]:
#단위행렬만들기
#대각선 1값 나머지 0 /정사각형
# np.eye(n)

In [ ]:
np.eye(4)

In [ ]:
#넘파이 배열 데이터 타입 변경
#astype()
#첫번째 키워드 인수 dtype 값 필수 입력

In [ ]:
a = np.ones((2,3,2))
a

In [ ]:
a.astype("i")

In [ ]:
np.random.seed(0)
d = np.random.randint(0,2,9)
d.astype("bool").reshape(3,3)

In [ ]:
#연습문제

In [1]:
import numpy as np

In [80]:
np.random.seed(0)
s = np.random.rand(10)
w = s * 10
w.astype("i")

array([5, 7, 6, 5, 4, 6, 4, 8, 9, 3], dtype=int32)

In [82]:
a = np.ones((10,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [83]:
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [84]:
a[1:9,1:9]=0
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [110]:
a = np.ones((10,10))
# a[0:,:1]=0
# a[0,]=0
# a[9:,]=0
# a[:,9:]=0

# a[:] = 0
# a[1:-1,1:-1]=1

a[:, [0,-1]] = 0
a[[0,-1], :] = 0
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [137]:
x = np.ones((8,8))
x[1::2,::2]=0
x[::2,1::2]=0
x

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [152]:
a = np.tile(np.eye(2),(4,4))
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [ ]:
boolean indexing
: 같은 shape와 len의 boolean의 값을 갖는 것 인덱싱
True면 값을 취하고 False면 가져오지 않는다

In [168]:
a = np.arange(11)
x = np.array([a[i]*-1 if 3<a[i]<7 else a[i] for i in range(11)])
print(x)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [169]:
a= np.arange(11)
a[(3<a)&(7>a)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6  7  8  9 10]


In [175]:
a = np.arange(3,100,3)
np.sum(a)


1683

In [180]:
np.linspace(0.1,0.9,9)

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [3]:
import numpy as np

while True:
    try:
        count = int(input("자연수를 입력해주세요."))
        if count <= 0:
            raise Error
        numbers = np.arange(1,46)
        x = [np.sort(np.random.choice(numbers,6, replace=False)) for _ in range(count)]
        display(x)
        break
    except:
        print("자연수만 입력해주세요")

자연수를 입력해주세요. 6


[array([ 3,  9, 13, 16, 28, 44]),
 array([ 2,  6,  7, 16, 20, 45]),
 array([ 2,  7, 20, 22, 25, 29]),
 array([15, 27, 28, 31, 38, 43]),
 array([ 6,  7, 15, 21, 28, 35]),
 array([ 1,  2,  8, 12, 30, 35])]

In [3]:
while True:
    n = input("자연수를 입력해주세요.")
    try:
        for i in range(int(n)):
            k = np.array([np.random.choice(np.arange(46), replace=False) for _ in range(6)])
            print(np.sort(k))
        break;
    except ValueError:
        print("자연수만 입력해주세요.")

자연수를 입력해주세요. 3


[ 4 10 16 27 30 32]
[ 5 23 25 29 32 44]
[ 7 11 16 21 33 42]


In [4]:
try:
    y = int(input("자연수만 입력해 주세요"))
    x = np.stack(np.random.randint(1,46, size=6) for i in range (y))
    print(x)
    
except:
    y = (input("자연수만 입력해 주세요"))

자연수만 입력해 주세요 3


[[44 26 32 24 16  9]
 [38 10  1 22  6  6]
 [33  4 24 35 13 28]]


C:\Users\jaehee\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3377: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  if (await self.run_code(code, result,  async_=asy)):


In [5]:
while True:
    try:
        n1 = int(input())
        if n1 <= 0:
            print("자연수만 입력해주세요.")
            continue
        else:
            for i in range(n1):
                lis = []
                a18= np.random.choice(range(1, 46), 6, replace = False)
                lis.extend(a18)
                lis.sort()
                print(lis)
        break
    except ValueError:
        print("자연수만 입력해주세요.")
        continue

 6


[5, 8, 11, 37, 38, 41]
[1, 4, 20, 30, 37, 44]
[10, 18, 24, 29, 34, 36]
[1, 3, 20, 25, 32, 35]
[7, 9, 21, 28, 29, 43]
[2, 5, 25, 30, 31, 41]


In [9]:
r = np. array([158,  85, 205,  24,  42, 175, 188, 149, 153, 171, 137,  55, 108,
                       199, 177, 209, 218,  76, 103, 189, 110, 192, 136, 119,   4, 102,
                       177, 212, 110,  37, 163,  32,  77,  22, 125, 184,  46, 139,  72,
                       168, 133, 209, 148,  47, 102,  65, 160,  56,  11,  96, 169, 118,
                        55, 135, 217,  49, 100,  85, 179,  15, 139, 199, 124, 142,  15,
                        49, 168, 171, 168, 177, 147,  23, 199,  26,  51,  42,  90, 128,
                       186, 169, 129,  70, 198, 111,  81, 150,  17, 177, 201,  10,  75,
                       199,  55, 151, 183, 152, 119, 193, 110, 204])

len(r[r>200])


8

In [13]:
np.percentile(r,0),np.percentile(r,25),np.percentile(r,50),np.percentile(r,75)

(4.0, 71.5, 131.0, 175.5)

In [35]:
p = ["뽀로로", "루피", "크롱"]
result = np.array([2, 1, 2, 2, 2, 2, 0, 2, 1, 1, 0, 0, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1,
                   1, 2, 0, 2, 2, 0, 1, 1, 0, 2, 1, 0, 1, 2, 0, 0, 1, 0, 1, 1, 1, 2,
                   1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 2, 0, 2, 2, 0, 0, 1, 1, 1, 0, 0, 2,
                   2, 1, 0, 1, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0,
                   2, 0, 0, 0, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0, 1, 2, 1, 2, 0, 2, 2, 1,
                   2, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 0, 2, 0, 2,
                   1, 1, 2, 1, 1, 0, 0, 1, 0, 0, 0, 2, 2, 0, 2, 0, 0, 0, 2, 0, 0, 0,
                   2, 0, 1, 2, 1, 0, 2, 0, 0, 1, 2, 1, 1, 2, 2, 0, 0, 0, 0, 2, 2, 1,
                   0, 1, 1, 2, 2, 1, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 1, 0, 0, 2,
                   0, 1])
index, count = np.unique(result, return_counts=True)
print(p[np.argmax(count)],"가",max(count),"표로 반장으로 선출되었습니다.")

뽀로로 가 81 표로 반장으로 선출되었습니다.


In [36]:
count = np.bincount(result, minlength = 3)
win = count.argmax()
print(f'{p[win]}가 {count[win]}표로 반장으로 선출되었습니다.')

뽀로로가 81표로 반장으로 선출되었습니다.
